[package]
name = "cheminee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1"
clap = "3.1"
env_logger = "0"
eyre = "0"
log = "0"
rdkit = "0.2.9"
regex = "1"
reqwest = "0"
serde_json = { version = "1" }
tantivy = "0.17.0"
tokio = { version = "1", features = ["full"] }
