FROM ubuntu

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y  \
      ca-certificates curl git vim sudo wget \
    - sudo apt-get update &&  sudo apt-get upgrade -y && sudo apt-get install -y curl vim git \
      libboost-all-dev build-essential g++ python3-dev  autotools-dev libicu-dev libbz2-dev \
      libschroedinger-maeparser-dev libeigen3-dev  cmake llvm  ca-certificates libssl-dev  libfreetype6-dev  libclang-dev \
      mkdir coordgen && cd coordgen && git clone https://github.com/schrodinger/coordgenlibs.git && \
      cd coordgenlibs && mkdir build && cd build/ && cmake .. && sudo make -j install && cd ../../..  \
      curl && \
      curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl  && \
      chmod +x ./kubectl  && \
      mv ./kubectl /usr/local/bin && \
      rm -rf /var/cache/apk/*

ADD target/cross/x86_64-unknown-linux-musl/release/cheminee /usr/bin/cheminee