FROM ubuntu

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y  \
      ca-certificates curl git vim sudo wget \
    - apt-get update && apt-get -y install apt-transport-https build-essential ca-certificates gnupg libatlas-base-dev \
      libboost-all-dev libeigen3-dev libgoogle-glog-dev libhdf5-serial-dev libprotobuf-dev librdkit-dev linux-headers-generic \
      protobuf-compiler python3-dev python3-numpy python3-pip software-properties-common swig catch \
      pkg-config libssl-dev gcc libfreetype6-dev libclang-dev libssl-dev cmake llvm catch  libfreetype6-dev \
      mkdir maeparser && cd maeparser && git clone https://github.com/schrodinger/maeparser.git \
      cd maeparser && mkdir build && cd build && cmake .. && sudo make -j install && cd ../../.. \
      mkdir coordgen && cd coordgen && git clone https://github.com/schrodinger/coordgenlibs.git \
      cd coordgenlibs && mkdir build && cd build/ && cmake .. && sudo make -j install && cd ../../.. \
      curl && \
      curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl  && \
      chmod +x ./kubectl  && \
      mv ./kubectl /usr/local/bin && \
      rm -rf /var/cache/apk/*

ADD target/cross/x86_64-unknown-linux-musl/release/cheminee /usr/bin/cheminee