FROM alpine

RUN apk add --update \
      ca-certificates \
      bash boost boost-dev llvm \
      curl && \
      curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl  && \
      chmod +x ./kubectl  && \
      mv ./kubectl /usr/local/bin && \
      rm -rf /var/cache/apk/*

ADD target/aarch64-unknown-linux-musl/release/cheminee /usr/bin/cheminee